--changeset tdep:2
do $$
    begin
        create type "entry_types" as enum (
            'JOB',
            'PROJECT',
            'CONTACT',
            'LINK',
            'TOOL',
            'URL'
            );
        create type "link_types" as enum (
            'IMAGE',
            'GITHUB',
            'DEMO',
            'LINKEDIN',
            'EXTERNAL_PORTFOLIO'
            );
        exception when duplicate_object then null;
    end $$;




create table if not exists "portfolio_entries" (
    entry_id smallint not null generated by default as identity,
    entry_name varchar(50) not null,
    entry_type entry_types,
    primary key (entry_id)
);

create table if not exists "urls" (
    url_id smallint not null generated by default as identity,
    url_name varchar(50) not null,
    url varchar(1024) not null,
    entry_id smallint not null references portfolio_entries (entry_id),
    primary key (url_id)
);

create table if not exists "projects" (
    project_id smallint not null generated by default as identity,
    project_name varchar(50) not null,
    project_description varchar(1024) not null,
    entry_id smallint not null references portfolio_entries (entry_id),
    primary key (project_id)
);

create table if not exists "links" (
    link_id smallint not null generated by default as identity,
    link_name varchar(50) not null,
    url_id smallint not null references urls (url_id),
    entry_id smallint not null references portfolio_entries (entry_id),
    link_type link_types,
    project_id smallint references projects (project_id),
    primary key (link_id)
);

create table if not exists "tools" (
    tool_id smallint not null generated by default as identity,
    tool_name varchar(50) not null,
    project_id smallint references projects (project_id),
    link_id smallint not null references links (link_id),
    entry_id smallint not null references portfolio_entries (entry_id),
    primary key (tool_id)
);

