--changeset tdep:1
drop table "projects" cascade;

create table if not exists "projects" (
    id integer not null generated by default as identity,
    title varchar(255) not null,
    description varchar(1024) not null,
    image_url varchar(255) not null,
    primary key (id)
);