--changeset tdep:2
create type "entry_types" as enum (
    'JOB',
    'PROJECT',
    'CONTACT',
    'LINK',
    'TOOL',
    'URL'
);

create type "link_types" as enum (
    'IMAGE',
    'GITHUB',
    'DEMO',
    'LINKEDIN',
    'EXTERNAL_PORTFOLIO'
);

create table if not exists "portfolio_entries" (
    id smallint not null generated by default as identity,
    name varchar(50) not null,
    entry_type entry_types,
    primary key (id)
);

create table if not exists "urls" (
    id smallint not null generated by default as identity,
    name varchar(50) not null,
    url varchar(1024) not null,
    entry_id smallint not null references portfolio_entries (id),
    primary key (id)
);

create table if not exists "projects" (
    id smallint not null generated by default as identity,
    name varchar(50) not null,
    description varchar(1024) not null,
    entry_id smallint not null references portfolio_entries (id),
    primary key (id)
);

create table if not exists "links" (
    id smallint not null generated by default as identity,
    name varchar(50) not null,
    url_id smallint not null references urls (id),
    entry_id smallint not null references portfolio_entries (id),
    link_type link_types,
    project_id smallint references projects (id),
    primary key (id)
);

create table if not exists "tools" (
    id smallint not null generated by default as identity,
    name varchar(50) not null,
    project_id smallint references projects (id),
    link_id smallint not null references links (id),
    entry_id smallint not null references portfolio_entries (id),
    primary key (id)
);

