--changeset tdep:2
drop table "tools";

create table if not exists "tools" (
    id integer Not Null generated by default as identity,
    name varchar(255) not null,
    image_url varchar(255) not null,
    project_id integer not null references projects (id),
    primary key (id)
);