--changelog tdep:3

create table if not exists "projects" (
    id smallint not null generated by default as identity,
    name varchar(255) not null,
    entry_type entry_types,
    description varchar(1024) not null,
    primary key (id)
);

create table if not exists "tools" (
    id smallint not null generated by default as identity,
    name varchar(255) not null,
    entry_type entry_types,
    primary key (id)
);

create table if not exists "project_tools" (
    project_id smallint not null references projects (id),
    tool_id smallint not null references tools (id),
    constraint  project_tools_pk primary key (project_id, tool_id)
);