--changeset tdep:2
create type "entry_types" as enum (
    'JOB',
    'PROJECT',
    'CONTACT',
    'LINK',
    'TOOL'
);

create type "url_types" as enum (
    'IMAGE',
    'GITHUB',
    'DEMO',
    'LINKEDIN',
    'EXTERNAL_PORTFOLIO'
);

create table if not exists "portfolio_entries" (
    id smallint not null generated by default as identity,
    name varchar(255) not null,
    entry_type entry_types,
    primary key (id)
);

create table if not exists "urls" (
    id smallint not null generated by default as identity,
    name varchar(255) not null,
    url varchar(1024) not null,
    url_type url_types,
    primary key (id)
);

create table if not exists "portfolio_entry_urls" (
    portfolio_entry_id smallint,
    url_id smallint,
    primary key (portfolio_entry_id, url_id),
    constraint fk_portfolio_entry_id foreign key (portfolio_entry_id) references portfolio_entries(id),
    constraint fk_url_id foreign key (url_id) references urls(id)
);

-- create table if not exists "projects" (
--     id smallint not null generated by default as identity,
--     name varchar(255) not null,
--     entry_type entry_types,
--     description varchar(1024) not null,
--     primary key (id)
-- );
--
-- create table if not exists "tools" (
--     id smallint not null generated by default as identity,
--     name varchar(255) not null,
--     entry_type entry_types,
--     primary key (id)
-- );
--
-- create table if not exists "project_tools" (
--     project_id smallint not null references projects (id),
--     tool_id smallint not null references tools (id),
--     constraint  project_tools_pk primary key (project_id, tool_id)
-- );