--changeset tdep:3
drop table "project_links";

create type link_type as enum ('github', 'demo');

create table if not exists "project_links" (
    id integer not null generated by default as identity,
    name varchar(255) not null,
    url varchar(255) not null,
    link_type link_type,
    project_id integer not null references projects (id),
    primary key (id)
);